import "../globals.css";
import Navbar from "@/components/frontend/Navbar";
import Footer from "@/components/frontend/Footer";
import {CartProvider} from "@/context/CartContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <CartProvider>

      <Navbar/>
      {children}
      <div className="mt-96">
      <Footer/>
      </div>
      </CartProvider>
      </body>
    </html>
  );
}
